baseurl = "https://blog.nucleognulinux.org"
title = "Nucleo Gnu/Linux"
author = "Nucleo Gnu/Linux"
canonifyurls = true
paginate = 3
theme = "aether"
googleAnalytics = "Your google analytics tracking ID - optional"
disqusShortname = "blog-nucleognulinux-org"

[params]
brand = "Nucleo Gnu/Linux"
description = "aether Hugo theme for blogs"
bgimg = "img/ignasi_pattern_s.png"
homeimg = "URL to the image used for the home button at the bottom of each post - optional"
